import typing


@typing.runtime_checkable
class BinaryFileLike(typing.Protocol):
    def read(self, size: int = -1) -> bytes: ...
    def seek(self, offset: int, whence: int = 0) -> int: ...
    def tell(self) -> int: ...
    def close(self): ...
